# 二、Numpy
## 1. Numpy 基本數學函數

In [1]:
import numpy as np
from numpy.ma.core import cumsum, concatenate

In [4]:
# 計算平方根（返回結果是浮點數）
print(np.sqrt(9))
print(np.sqrt([1, 4, 9]))

arr = np.array([1, 25, 81])
print(np.sqrt(arr))

3.0
[1. 2. 3.]
[1. 5. 9.]


In [7]:
# 計算指數 e^x = y
print(np.exp(1)) # 自然數e

2.718281828459045


In [8]:
# 計算自然對數 ln y = x
print(np.log(2.71))

0.9969486348916096


In [9]:
# 計算三角函數中的正弦值、餘弦值
print(np.sin(-1))
print(np.cos(np.pi))

-0.8414709848078965
-1.0


In [10]:
# 計算絕對值
arr = np.array([1, 2, -3, -9])
print(np.abs(arr))

[1 2 3 9]


In [12]:
# 計算a的b次方
print(np.power(arr, 3))

[   1    8  -27 -729]


In [18]:
# 四捨五入
print(np.round([4.213, 5.3, 2.78, 7.53, 5.5, 4.5]))
# 注意：「向偶數捨入」(Round half to even)，也稱為「銀行家捨入法」(Banker's Rounding)
# 即「向最近的偶數靠攏」 --> 4.5 靠近 4, 5.5 靠近 6

[4. 5. 3. 8. 6. 4.]


In [19]:
# 向上取整，向下取整
arr = np.array([4.213, 5.3, 2.78, 7.53, 5.5, 4.5])
print(np.ceil(arr))
print(np.floor(arr))

[5. 6. 3. 8. 6. 5.]
[4. 5. 2. 7. 5. 4.]


In [21]:
# 檢測缺失值NaN
np.isnan([1, 2, np.nan, 3])

array([False, False,  True, False])

## 2. 統計函數
### 求和、平均值、中位數、標準差、變異數
### 最大值、最小值
### 分位數、累積和、累積差

In [24]:
arr = np.random.randint(1, 20, 8)
print(arr)

[17 10  3  7 14 11  1 16]


In [31]:
# 求和
print(np.sum(arr))
print(np.sum([1, 2, 3]))

79
6


In [32]:
# 計算平均值
print(np.mean([1, 2, 3]))

2.0


In [36]:
# 計算中位數
# 奇數：中位數是正中間那一位數
# 偶數：中位數是中間兩位數的「平均值」
print(np.median([1, 2, 4])) 
print(np.median([1, 2, 4, 8])) 

2.0
3.0


In [112]:
# 計算標準差＆變異數
# [1, 2, 3]平均值為2
# 標準差 = ((1-2)^2 + (2-2)^2 + (3-2)^2)/ 3 = 0.66666
# 變異數 = 標準差^1/2
print('標準差：', np.var([1, 2, 3]))
print('變異數：', np.std([1, 2, 3]))

標準差： 0.6666666666666666
變異數： 0.816496580927726


In [41]:
# 計算最大值＆最小值以及位置
print(arr)
print(np.max(arr), np.argmax(arr))
print(np.min(arr), np.argmin(arr))

[17 10  3  7 14 11  1 16]
17 0
1 6


In [53]:
# 分位數
np.random.seed(0)
arr = np.random.randint(0, 100, 8)
arr.sort() # 由小到大進行排序
print(arr)

print(np.median(arr))
print(np.percentile(arr, 50))
print(np.percentile(arr, 25))
# 樣本分位數
# 定位方式：(n - 1) * 百分比  = (8 - 1) * 0.25 = 7 * 0.25 = 1.75
# 1.75拆成整數索引 = 1(21) ＆ 小數權重 = 0.75
# 結果 = 下界值+小數權重×(上界值−下界值)
print(np.percentile(arr, 80))

[ 9 21 44 47 64 67 67 83]
55.5
55.5
38.25
67.0


In [56]:
# 累積和＆累積積
arr = np.array([1, 2, 3])
print(np.sum(arr))
print(np.cumsum(arr))
print(np.cumprod(arr))

6
[1 3 6]
[1 2 6]


## 3. 比較函數
### 比較是否大於、小於或是等於
### 邏輯「與」、「或」、「非」
### 檢查陣列中是否有一個True、是否所有都為True、自定義條件

In [84]:
# 是否大於
print(np.greater([3, 4, 5, 6, 7, 8],4))
# 是否小於
print(np.less([3, 4, 5, 6, 7, 8],4))
# 是否等於
print(np.equal([3, 4, 5, 6, 7, 8],4))
print(np.equal([3, 4, 5], [4, 4, 4]))

# 大於等於： np.greater_equal()
print(np.greater_equal([3, 4, 5, 6, 7, 8],4))
# 小於等於： np.less_equal()
print(np.less_equal([3, 4, 5, 6, 7, 8],4))

[False False  True  True  True  True]
[ True False False False False False]
[False  True False False False False]
[False  True False]
[False  True  True  True  True  True]
[ True  True False False False False]


In [67]:
# 邏輯「與」
print(np.logical_and([1, 0, 1], [1, 1, 0]))
# 邏輯「或」
print(np.logical_or([1, 0, 1], [1, 1, 0]))
# 邏輯「非」
print(np.logical_not([1, 0, 1]))

[ True False False]
[ True  True  True]
[False  True False]


In [81]:
# 檢查元素是否至少有一個為True
print(np.any([1, 1, 0, 0, 0, 1, 0]))
print(np.any([0, 0, 0, 0, 0, 0, 0]))
# 檢查元素是否全部為True
print(np.all([1, 1, 0, 0, 0, 1, 0]))
print(np.all([1, 1, 1, 1, 1, 1, 1]))

True
False
False
True


### 自定義條件

In [72]:
# print(np.where(條件, 符合條件, 不符合條件))
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(np.where(arr>5, 0, arr))

[1 2 3 4 5 0 0 0 0]


In [77]:
# 範例：考試分數
score = np.random.randint(40, 100, 10)
print(score)
print(np.where(score>=60, "及格", "不及格"))

[60 91 56 91 45 55 87 40 58 75]
['及格' '及格' '不及格' '及格' '不及格' '不及格' '及格' '不及格' '不及格' '及格']


In [76]:
# 嵌套方式
# 範例：評分分為"甲"、"乙"、"丙"
print(score)
print(np.where(
    score<60, "丙", np.where(
        score<80, "乙", "甲"
    ) 
))

[79 63 86 64 57 77 65 53 48 49]
['乙' '乙' '甲' '乙' '丙' '乙' '乙' '丙' '丙' '丙']


In [80]:
# np.select(條件, 返回結果, default = 不符合條件)
print(score)
print(np.select([score>=80, (score<80) & (score>=60),score<60], ["甲", "乙", "丙"], default="缺考"))

[60 91 56 91 45 55 87 40 58 75]
['乙' '甲' '丙' '甲' '丙' '丙' '甲' '丙' '丙' '乙']


In [86]:
# if 語句搭配 for 迴圈
print(score)
result_list = []

for s in score:
    if s < 60:
        result_list.append("丙")
    elif s < 80: # 這裡不用寫 s>=60，因為第一個 if 已經排除了小於60的情況
        result_list.append("乙")
    else: # 剩下的就是大於等於 80 的情況
        result_list.append("甲")

print(np.array(result_list))

[60 91 56 91 45 55 87 40 58 75]
['乙' '甲' '丙' '甲' '丙' '丙' '甲' '丙' '丙' '乙']


In [91]:
# 排序函數
np.random.seed(0)
arr = np.random.randint(1, 100, 20)
print(arr)
# 不影響原始數據
print(np.sort(arr))
print(np.argsort(arr)) # 對應排序位置
print(arr)

# 影響原始數據
# arr.sort()
# print(arr)

[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
[10 13 22 37 40 45 47 48 59 65 66 68 68 71 84 88 88 89 89 89]
[ 5 13  7  8 16  0 18  1 14  2 15  3  4 10  6  9 17 11 12 19]
[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]


In [92]:
# 去重函數
print(np.unique(arr)) #同時進行排序

[10 13 22 37 40 45 47 48 59 65 66 68 71 84 88 89]


In [110]:
# 陣列的拼接
# 一維
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 + arr2)
print(np.concatenate((arr1, arr2)))

# 二維
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
arr4 = np.array([[4, 5, 6], [7, 8, 9]])
print(arr3 + arr4)
result = np.concatenate((arr3, arr4))
print(np.concatenate((arr3, arr4)))
print("陣列的形狀是:", result.shape) 

[5 7 9]
[1 2 3 4 5 6]
[[ 5  7  9]
 [11 13 15]]
[[1 2 3]
 [4 5 6]
 [4 5 6]
 [7 8 9]]
陣列的形狀是: (4, 3)


In [100]:
# 陣列的分割
print(np.split(arr, 4)) # 切割必須要是等分的，否則報錯
print(np.split(arr, [6, 12, 18])) # 或是給切割位置索引

[array([45, 48, 65, 68, 68], dtype=int32), array([10, 84, 22, 37, 88], dtype=int32), array([71, 89, 89, 13, 59], dtype=int32), array([66, 40, 88, 47, 89], dtype=int32)]
[array([45, 48, 65, 68, 68, 10], dtype=int32), array([84, 22, 37, 88, 71, 89], dtype=int32), array([89, 13, 59, 66, 40, 88], dtype=int32), array([47, 89], dtype=int32)]


In [104]:
# 調整陣列形狀 (需要能等分的)
print(np.reshape(arr, [4, 5]))
print(np.reshape(arr, [2, 10]))

[[45 48 65 68 68]
 [10 84 22 37 88]
 [71 89 89 13 59]
 [66 40 88 47 89]]
[[45 48 65 68 68 10 84 22 37 88]
 [71 89 89 13 59 66 40 88 47 89]]
