# Numpy 練習

### 題目1：溫度資料分析
### 某城市一週的最高溫為[28,30,29,31,32,30,29]。
### - 計算平均氣溫、最高氣溫和最低氣溫。
### - 找出氣溫超過30度的天數。

In [32]:
from array import array
from itertools import count

import numpy as np

temps = np.array([28,30,29,31,32,30,29])
print(temps)

print('平均氣溫：', '%.3f'%np.mean(temps))
print('最高氣溫：',np.max(temps))
print('最低氣溫：',np.min(temps))
print('氣溫超過30的天數：', len(temps[temps>30]))

# 其他解法
# print('氣溫超過30的天數：', temps[temps>30].size)
# print('氣溫超過30的天數：', np.sum(temps>30))
# print('氣溫超過30的天數：', np.cumsum(np.where(temps>30, 1, 0))[-1])
# print('氣溫超過30的天數：', np.sum(np.where(temps>30, 1, 0)))
# print('氣溫超過30的天數：', np.count_nonzero(temps>30))

[28 30 29 31 32 30 29]
平均氣溫： 29.857
最高氣溫： 32
最低氣溫： 28
氣溫超過30的天數： 2


### 題目2：學生成績統計
### 某班級5名學生的數學成績為[85,90,78,92,88]
### - 計算成績的平均分數、中位數和標準差。
### - 將成績轉換為十分制(假設滿分為 10)。

In [43]:
score = np.array([85,90,78,92,88])
print(score)
print(np.sort(score))
print("5名學生的平均分：", np.mean(score))
print("5名學生的中位數：", np.median(score))
print("5名學生的變異數：", np.var(score))
print("5名學生的標準差：%.3f"% np.std(score))
print("5名學生的成績：", score / 10)

[85 90 78 92 88]
[78 85 88 90 92]
5名學生的平均分： 86.6
5名學生的中位數： 88.0
5名學生的標準差： 23.84
5名學生的方差：4.883
5名學生的成績： [8.5 9.  7.8 9.2 8.8]


### 題目3：矩陣運算
### 給定矩陣A=[[1, 2],[3, 4]]和B=[[5, 6],[7, 8]]。
### - 計算A+B和A*B(逐元素乘法)。
### - 計算A和B的矩陣乘法(點積)。

In [49]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A)
print(B)

print(A + B)
print(A * B)
# print(A @ B)
print(np.dot(A,B))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


### 題目4:隨機資料生成
### 產生一個(3,4)的隨機整數陣列,範圍[0,10)。
### - 計算每列的最大值和每行的最小值。
### - 將陣列中的所有奇數替換為-1。

In [63]:
np.random.seed(0)
arr = np.random.randint(0,10, [3,4])
print(arr)
print("每列的最大值：", np.max(arr, axis=0))  # 列：axis=0, 行：axis=1 
print("每行的最小值：", np.min(arr, axis=1))
# print("所有基數替換為-1：", np.where(arr%2 == 1, -1, arr))
arr[arr%2 == 1] = -1
print(arr)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
每列的最大值： [7 9 7 6]
每行的最小值： [0 3 2]
[[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]


### 題目5:陣列變形
### 建立一個1到12的一維陣列,並轉換為(3,4)的二維陣列。
### - 計算每行的和與每列的平均值。
### - 將陣列展平為一維陣列。

In [75]:
arr = np.arange(1, 13)
print(arr)

print(np.reshape(arr,(3,4)))
print("每行的和", np.sum(np.reshape(arr,(3,4)), axis=1))
print("每列的平均值", np.mean(np.reshape(arr,(3,4)), axis=0))
print(np.reshape(np.reshape(arr,(3,4)),(12)))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
每行的和 [10 26 42]
每列的平均值 [5. 6. 7. 8.]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


### 題目6:布林索引
### 產生一個(5,5)的隨機數組,範圍 [0,20)。
### - 找出數組中大於 10 的元素。
### - 將所有大於 10 的元素替換為 0。

In [83]:
np.random.seed(0)
arr = np.random.randint(0,20, [5,5])
print(arr)
print(arr[arr > 10])
print(np.where(arr > 10, 0, arr))

[[12 15  0  3  3]
 [ 7  9 19 18  4]
 [ 6 12  1  6  7]
 [14 17  5 13  8]
 [ 9 19 16 19  5]]
[12 15 19 18 12 14 17 13 19 16 19]
[[0 0 0 3 3]
 [7 9 0 0 4]
 [6 0 1 6 7]
 [0 0 5 0 8]
 [9 0 0 0 5]]


### 題目7:統計函數應用
### 某公司6個月的銷售額(萬元)為[120,135,110,125,130,140]。
### - 計算銷售額的總和、平均值和變異數。
### - 找出銷售額最高的月份和最低的月份。

In [92]:
money = np.array([120,135,110,125,130,140])
print(money)
print("銷售額總和(萬元)：", np.sum(money))
print("銷售額平均值(萬元)：%.3f"% np.mean(money))
print("銷售額變異數：%.3f"% np.var(money))
print("銷售額標準差：%.3f"% np.std(money))
print("銷售額最高的月份：", np.argmax(money) + 1)
print("銷售額最低：", np.argmin(money) + 1)

[120 135 110 125 130 140]
銷售額總和(萬元)： 760
銷售額平均值(萬元)：126.667
銷售額標準差：97.222
銷售額變異數：9.860
銷售額最高的月份： 6
銷售額最低： 3


### 題目8:陣列拼接
### 給定A=[1,2,3]和B=[4,5,6]。
### - 將A和B水平拼接為一個新數組。
### - 將A和B垂直拼接為一個新數組。

In [106]:
A = np.array([1,2,3])
B = np.array([4,5,6])
print(A)
print(B)

# 水平拼接
C = np.concatenate((A,B))
print(C)

# 垂直拼接
D = np.reshape(A,(3,1))
E = np.reshape(B,(3,1))
print(np.concatenate((D,E), axis = 1))

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]


### 題目9:唯一值與排序
### 給定陣列[2,1,2,3,1,4,3]
### - 找出群組中的唯一值並排序。
### - 計算每個唯一值出現的次數。

In [119]:
arr = np.array([2,1,2,3,1,4,3])
print(arr)
# print(np.unique(arr))

# 「多重賦值 (Multiple Assignment)」
U_arr, counts = np.unique(arr, return_counts=True)
print(U_arr)
print(counts)

# for 循環
d = []
for i in range(len(U_arr)):
    # print(len(arr[arr == U_arr[i]]))
    d = d + [len(arr[arr == U_arr[i]])]
print(d)

[2 1 2 3 1 4 3]
[1 2 3 4]
[2 2 2 1]
[2, 2, 2, 1]


### 題目10:綜合應用
### 某商店5天的銷售額(萬元)和成本(萬元)如下:
### 銷售額:[20, 25, 22, 30, 28]
### 成本:[15, 18, 16, 22, 20]
### - 計算每天的利潤(銷售額-成本)。
### - 計算利潤的平均值和標準差。
### - 求出利潤最高的天數。

In [137]:
money = np.array([20, 25, 22, 30, 28])
A = np.array([15, 18, 16, 22, 20])
print("每天利潤：", money - A)
b = money - A
print("利潤平均值：",np.mean(b))
print("利潤變異數：",np.var(b))
print("利潤標準差：",np.std(b))
print("利潤最高的天數：", len(b[b == np.max(b)]))
print(f"利潤最高的是第 {np.where(b == np.max(b))[0]+1} 天")

每天利潤： [5 7 6 8 8]
利潤平均值： 6.8
利潤變異數： 1.3599999999999999
利潤標準差： 1.16619037896906
利潤最高的天數： 2
利潤最高的是第 [4 5] 天
