# 一、Ndarray
## 1. ndarray 的特性
### 多維性

In [1]:
import numpy as np

In [2]:
# arr = numpy.array(5) 原本是這樣，但前面有設定numpy as np
arr = np.array(5) # 創建0維的ndarray陣列
print(arr)
print('arr的維度：', arr.ndim) # 陣列的維度 ndim = number of dimensions

5
arr的維度： 0


In [3]:
arr = np.array([1, 2, 3]) # 創建1維的ndarray陣列
print(arr)
print('arr的維度：', arr.ndim) # 陣列的維度 ndim = number of dimensions

[1 2 3]
arr的維度： 1


In [4]:
arr = np.array([ [1, 2, 3], [4, 5, 6]]) # 創建2維的ndarray陣列
print(arr)
print('arr的維度：', arr.ndim) # 陣列的維度 ndim = number of dimensions

[[1 2 3]
 [4 5 6]]
arr的維度： 2


### 同質性

In [5]:
arr = np.array([1, "hello"]) # 陣列中不同的數據類型，會被強制轉換成相同的數據類型 
print(arr)

['1' 'hello']


In [6]:
arr = np.array([1, 2.5]) # 陣列中不同的數據類型，會被強制轉換成相同的數據類型 
print(arr)

[1.  2.5]


## 2. ndarray 的屬性

In [7]:
arr = np.array(1)
print(arr)
print('陣列的形狀：', arr.shape)
print('陣列的維度：', arr.ndim)
print('元素的個數：', arr.size)
print('元素的數據類型：', arr.dtype)
print('元素的轉置：', arr.T)

1
數組的形狀： ()
數組的維度： 0
元素的個數： 1
元素的數據類型： int64
元素的轉置： 1


In [8]:
arr = np.array([1, 2.5, 3])
print(arr)
print('陣列的形狀：', arr.shape)
print('陣列的維度：', arr.ndim)
print('元素的個數：', arr.size)
print('元素的數據類型：', arr.dtype)
print('元素的轉置：', arr.T)

[1.  2.5 3. ]
數組的形狀： (3,)
數組的維度： 1
元素的個數： 3
元素的數據類型： float64
元素的轉置： [1.  2.5 3. ]


In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print('陣列的形狀：', arr.shape)
print('陣列的維度：', arr.ndim)
print('元素的個數：', arr.size)
print('元素的數據類型：', arr.dtype)
print('元素的轉置：', arr.T)

[[1 2 3]
 [4 5 6]]
數組的形狀： (2, 3)
數組的維度： 2
元素的個數： 6
元素的數據類型： int64
元素的轉置： [[1 4]
 [2 5]
 [3 6]]


## 3. ndarray 的創建

In [10]:
# 基礎的創建方法
# 後面有()是方法；後面沒有()是屬性
list1 = [4, 5, 6]
arr = np.array(list1, dtype=np.float64)
# arr = np.array([4, 5, 6])
print(arr.ndim) # 屬性
print(arr)

1
[4. 5. 6.]


In [11]:
# copy
arr1 = np.copy(arr) # 元素與原始的陣列相同，但是不是同一個陣列
print(arr1)
arr1[0] = 8 #修改arr1第一位數
print(arr1)
print(arr)

[4. 5. 6.]
[8. 5. 6.]
[4. 5. 6.]


In [12]:
# 預定義形狀
# 全0的陣列 全1的陣列 未初始化的陣列 固定值的陣列
# 全0的陣列
arr = np.zeros((2, 3))
print(arr)
print(arr.dtype)

arr = np.zeros((2, 3), dtype=int)
print(arr)
print(arr.dtype)

[[0. 0. 0.]
 [0. 0. 0.]]
float64
[[0 0 0]
 [0 0 0]]
int64


In [13]:
# 全1的陣列
arr = np.ones((5, 8), dtype=int)
print(arr)

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [14]:
# 未初始化的陣列
arr1 = np.empty((4, 2))
print(arr1)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [15]:
# 固定值的陣列
arr = np.full((3, 4), 2025)
print(arr)

[[2025 2025 2025 2025]
 [2025 2025 2025 2025]
 [2025 2025 2025 2025]]


In [16]:
# 補充：與其他陣列格式一樣
arr1 = np.zeros_like(arr) 
print(arr1)

arr1 = np.ones_like(arr) 
print(arr1)

arr1 = np.empty_like(arr) 
print(arr1)

arr1 = np.full_like(arr, 2026) 
print(arr1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[2026 2026 2026 2026]
 [2026 2026 2026 2026]
 [2026 2026 2026 2026]]


In [17]:
# 等差數列 ex. 2 4 6 8 10
arr = np.arange(1, 10, 1) # start ,end, step(步長)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [18]:
# 等間格數列
arr = np.linspace(0, 100, 5) # 起始, 終點, 間隔數
print(arr)

[  0.  25.  50.  75. 100.]


In [19]:
arr = np.linspace(0, 100, 5, dtype=int) # 起始, 終點, 間隔數
print(arr)
arr = np.arange(0, 101, 25)
print(arr)

[  0  25  50  75 100]
[  0  25  50  75 100]


In [20]:
# 對數間隔數列
arr = np.logspace(0, 4, 3, base=2) # 起始, 終點, 間隔數, 以X為底數(2^0, 2^2, 2^4)
print(arr)

[ 1.  4. 16.]


In [21]:
# 特殊矩陣
# 單位矩陣：主對角線上的數字為1，其他數字為0
arr = np.eye(3, dtype=int)
print(arr)

arr = np.eye(3, 4, dtype=int)
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [22]:
# 對角矩陣：主對角線上非零的數字，其他數字為0
arr = np.diag([1, 2, 3])
print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [23]:
# 隨機陣列的生成
# 生成0到1之間的隨機浮點數(均勻分布)
arr = np.random.randn(3, 4)
print(arr)

[[-0.79820187 -0.85556695  0.27680683  0.48426167]
 [-0.22761831 -0.68494137 -0.85890126  0.38812429]
 [ 0.33617204  0.14263701  1.39095039  0.01578666]]


In [24]:
# 生成指定範圍區間的隨機浮點數
arr = np.random.uniform(3, 6, (2, 3))
print(arr)

[[3.32046409 5.61575687 4.01275689]
 [5.98802164 5.84115144 5.92554945]]


In [25]:
# 生成指定範圍區間的隨機整數
arr = np.random.randint(3, 30, (2, 3))
print(arr)

[[ 6 21 23]
 [11 27 25]]


In [26]:
# 生成隨機數列（正態分布）
# randn 標準正態分布，平均值為 0，標準差為 1
# 兩側小，中間大
arr = np.random.randn(2, 3)
print(arr)

[[-0.72915476 -0.44881471  0.27180511]
 [ 0.89046368 -1.67067658 -0.90033786]]


In [27]:
# 設置隨機種子
# np.random.seed()的作用，不是讓數字「更隨機」，是為了讓「隨機」結果變得可以被控制和重現
np.random.seed(20)
arr = np.random.randint(1, 10, (2, 5))
print(arr)

[[4 5 7 8 3]
 [1 7 9 6 4]]


## 4. ndarray 的數據類型
### 布林類型 bool
### 整數類型 int, uint
### 浮點數類型 float
### 複數類型 complex

In [28]:
arr = np.array([1, 0, 2, 0], dtype='bool')
print(arr)

arr = np.array([1, 0, 2, 0], dtype=np.bool)
print(arr)

[ True False  True False]
[ True False  True False]


In [29]:
arr = np.array([1, 0, 2, 0], dtype=np.int8)
print(arr)

arr = np.array([1, 0, 2, 0], dtype=int)
print(arr)

# Error：超過範圍
# arr = np.array([1, 0, 2000, 0], dtype=np.int8)
# print(arr)

[1 0 2 0]
[1 0 2 0]


## 5. 索引與切片

In [30]:
# 一維陣列的索引與切片
arr = np.random.randint(1, 100, 20)
print(arr)

[17 63 17  8 99  7 27 14 76 59 26  4 75 76 62 78 84 58 95 33]


In [31]:
print(arr[10]) #基礎索引

print(arr[:]) # 獲取全部的數據

print(arr[2:5]) # start:end+1 左包右不包

print(arr[slice(2, 15, 3)]) # # start, end+1, step

print(arr[(arr > 10) & (arr < 70)]) # 布林索引

26
[17 63 17  8 99  7 27 14 76 59 26  4 75 76 62 78 84 58 95 33]
[17  8 99]
[17  7 76  4 62]
[17 63 17 27 14 59 26 62 58 33]


In [32]:
# 二維陣列的索引與切片
arr = np.random.randint(1, 100, (4, 8))
print(arr)

[[11  7 76 19  4 78 18 44]
 [17 19 80 91 60 72 76 30]
 [46  7 64 79 25 19 94 34]
 [79 43 95  4 19 71 53 23]]


In [33]:
print(arr[1, 3]) # 直接訪問/元組式訪問 --> 單一、高效的動作
print(arr[1][3]) # 鏈式訪問/項目式訪問 --> 兩步驟的過程

print(arr[:, :]) # 獲取全部的數據
print(arr[1, 2:5])

print(arr[arr > 50]) # 布林索引 --> 會返回一維陣列
print(arr[2][arr[2] > 50])
print(arr[2]>50) # 補充：「先索引第 2 行，再對該行所有元素做 > 50 的判斷，最終返回一個布林陣列」

print(arr[:, 3]) #針對列數據


91
91
[[11  7 76 19  4 78 18 44]
 [17 19 80 91 60 72 76 30]
 [46  7 64 79 25 19 94 34]
 [79 43 95  4 19 71 53 23]]
[80 91 60]
[76 78 80 91 60 72 76 64 79 94 79 95 71 53]
[64 79 94]
[False False  True  True False False  True False]
[19 91 79  4]


## 5. ndarray 的運算

In [34]:
# 一維np算術運算
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** 2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [35]:
# 原始運算
c = [1, 2, 3]
d = [4, 5, 6]
for i in range(len(c)):
    d[i] = c[i] + d[i]
    print(d[i])

5
7
9


In [36]:
# 二維np算術運算
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[4, 5, 6], [7, 8, 9], [1, 2, 3]])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** 2)

[[ 5  7  9]
 [11 13 15]
 [ 8 10 12]]
[[-3 -3 -3]
 [-3 -3 -3]
 [ 6  6  6]]
[[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]
[[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]
 [7.         4.         3.        ]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [37]:
# 陣列與標量之間的算術運算
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a + 3)
print(a * 3)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [38]:
# 廣播機制：1.獲取形狀 2.是否可以廣播 3.進行廣播
# 條件: 所有對應維度的大小必須相等，或是其中一個為 1。
a = np.array([1, 2, 3]) #1*3
b = np.array([[4], [5], [6]]) # 3*1
print(a + b)
print(b - a)
'''
擴展
a
    1 2 3
    1 2 3
    1 2 3
b
    4 4 4
    5 5 5
    6 6 6
'''

[[5 6 7]
 [6 7 8]
 [7 8 9]]
[[3 2 1]
 [4 3 2]
 [5 4 3]]


'\n擴展\na\n    1 2 3\n    1 2 3\n    1 2 3\nb\n    4 4 4\n    5 5 5\n    6 6 6\n'

In [39]:
# 錯誤範例：不同維度
# a = np.array([1, 2, 3]) #1*3
# b = np.array([4, 5]) # 1*2
# print(a + b)
# ValueError: operands could not be broadcast together with shapes (3,) (2,)

In [40]:
# 矩陣運算
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[4, 5, 6], [7, 8, 9], [1, 2, 3]])

# 「元素對應相乘」(Element-wise Multiplication)
print(a * b)

# 「矩陣乘法」(Matrix Multiplication)
# 求[n,m]的值，等於矩陣1的第n行的值依序乘以矩陣2的第m列的值，然後把相乘的結果求和，
print(a @ b)

[[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]
[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]
